# Generated by Django 5.1.7 on 2026-08-14 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de orden')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('description', models.TextField(verbose_name='descripción')),
                ('scheduled_date', models.DateField(verbose_name='fecha programada')),
                ('scheduled_time', models.TimeField(blank=True, null=True, verbose_name='hora programada')),
                ('service_address', models.CharField(blank=True, max_length=255, verbose_name='dirección del servicio')),
                ('priority', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='prioridad')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignado', 'Asignado'), ('en_labor', 'En labor'), ('realizado', 'Realizado'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='customer.customer', verbose_name='cliente')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='técnico asignado')),
            ],
            options={
                'verbose_name': 'orden de trabajo',
                'verbose_name_plural': 'órdenes de trabajo',
                'ordering': ['-scheduled_date', 'scheduled_time', '-created_at'],
            },
        ),
    ]
