# Generated by Django 5.1.7 on 2026-08-14 03:50

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('first_name', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras, espacios, apóstrofes y guiones.', regex="^[A-Za-zÁÉÍÓÚáéíóúÑñÜü\\s'-]+$")], verbose_name='nombres')),
                ('last_name', models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras, espacios, apóstrofes y guiones.', regex="^[A-Za-zÁÉÍÓÚáéíóúÑñÜü\\s'-]+$")], verbose_name='apellidos')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('tecnico', 'Técnico')], default='tecnico', max_length=20, verbose_name='rol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acceso al administrador')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['last_name', 'first_name', 'email'],
            },
        ),
    ]
