# Generated by Django 5.1.7 on 2026-08-28 05:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('responsible_name', models.CharField(blank=True, max_length=150, verbose_name='encargado(a)')),
                ('generator', models.CharField(blank=True, max_length=100, verbose_name='generador')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('kva', models.CharField(blank=True, max_length=30, verbose_name='KVA')),
                ('motor', models.CharField(blank=True, max_length=100, verbose_name='motor')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='serie')),
                ('battery_terminals_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('battery_terminals_observation', models.TextField(blank=True)),
                ('battery_water_level_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('battery_water_level_observation', models.TextField(blank=True)),
                ('battery_charger_load_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('battery_charger_load_observation', models.TextField(blank=True)),
                ('alternator_charger_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('alternator_charger_observation', models.TextField(blank=True)),
                ('oil_level_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('oil_level_observation', models.TextField(blank=True)),
                ('coolant_level_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('coolant_level_observation', models.TextField(blank=True)),
                ('radiator_physical_inspection_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('radiator_physical_inspection_observation', models.TextField(blank=True)),
                ('air_filter_inspection_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('air_filter_inspection_observation', models.TextField(blank=True)),
                ('preheater_inspection_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('preheater_inspection_observation', models.TextField(blank=True)),
                ('belt_tension_inspection_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('belt_tension_inspection_observation', models.TextField(blank=True)),
                ('fuel_tank_level_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('fuel_tank_level_observation', models.TextField(blank=True)),
                ('hose_clamps_inspection_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('hose_clamps_inspection_observation', models.TextField(blank=True)),
                ('electrical_terminals_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('electrical_terminals_observation', models.TextField(blank=True)),
                ('equipment_cleaning_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('equipment_cleaning_observation', models.TextField(blank=True)),
                ('intake_exhaust_muffler_flexible_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('intake_exhaust_muffler_flexible_observation', models.TextField(blank=True)),
                ('after_fire_inspection_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('after_fire_inspection_observation', models.TextField(blank=True)),
                ('oil_pressure_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('oil_pressure_observation', models.TextField(blank=True)),
                ('oil_temperature_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('oil_temperature_observation', models.TextField(blank=True)),
                ('coolant_temperature_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('coolant_temperature_observation', models.TextField(blank=True)),
                ('coolant_leaks_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('coolant_leaks_observation', models.TextField(blank=True)),
                ('oil_leaks_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('oil_leaks_observation', models.TextField(blank=True)),
                ('fuel_leaks_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('fuel_leaks_observation', models.TextField(blank=True)),
                ('frequency_rpm_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('frequency_rpm_observation', models.TextField(blank=True)),
                ('output_voltage_status', models.CharField(choices=[('OK', 'OK'), ('NO', 'NO')], max_length=2)),
                ('output_voltage_observation', models.TextField(blank=True)),
                ('general_observations', models.TextField(blank=True, verbose_name='observaciones y recomendaciones')),
                ('technician_name', models.CharField(max_length=150, verbose_name='técnico')),
                ('received_by', models.CharField(blank=True, max_length=150, verbose_name='recibido por')),
                ('technician_signature', models.TextField(blank=True, verbose_name='firma digital del técnico')),
                ('recipient_signature', models.TextField(blank=True, verbose_name='firma digital del recibido')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('terminado', 'Terminado')], default='borrador', max_length=15, verbose_name='estado del informe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_electrical_reports', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='electrical_report', to='workorder.workorder', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'informe de planta eléctrica',
                'verbose_name_plural': 'informes de plantas eléctricas',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
