# Generated by Django 5.1.7 on 2026-08-14 03:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Este campo solo puede contener letras, espacios, apóstrofes y guiones.', regex="^[A-Za-zÁÉÍÓÚáéíóúÑñÜü\\s'-]+$")], verbose_name='nombre del cliente')),
                ('identification', models.CharField(blank=True, max_length=30, verbose_name='identificación/NIT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Introduce un teléfono válido usando números, espacios, paréntesis o guiones.', regex='^\\+?[0-9 ()-]{7,20}$')], verbose_name='teléfono')),
                ('address', models.CharField(max_length=255, verbose_name='dirección')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
            },
        ),
    ]
