# Generated by Django 5.1.7 on 2026-08-14 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('work_order_assigned', 'Orden asignada'), ('work_order_status', 'Cambio de estado'), ('general', 'General')], default='general', max_length=30, verbose_name='tipo')),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='datos adicionales')),
                ('is_read', models.BooleanField(default=False, verbose_name='leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinatario')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workorder.workorder', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['is_read', '-created_at'],
            },
        ),
    ]
