# Generated by Django 5.1.7 on 2026-08-31 01:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workorder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha')),
                ('attention', models.CharField(blank=True, max_length=150, verbose_name='atención')),
                ('equipment_rows', models.JSONField(default=list, verbose_name='equipos en H.P.')),
                ('hydropneumatic_tank_brand', models.CharField(blank=True, max_length=100, verbose_name='marca tanque hidroneumático')),
                ('hydropneumatic_tank_determined_charge', models.CharField(blank=True, max_length=50, verbose_name='carga determinada')),
                ('hydropneumatic_tank_measured_charge', models.CharField(blank=True, max_length=50, verbose_name='carga medida')),
                ('speed_controller_brand', models.CharField(blank=True, max_length=100, verbose_name='marca controlador de velocidad')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('technician_name', models.CharField(max_length=150, verbose_name='técnico')),
                ('technician_signature', models.TextField(blank=True, verbose_name='firma digital del técnico')),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('terminado', 'Terminado')], default='borrador', max_length=15, verbose_name='estado del informe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pumping_reports', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pumping_report', to='workorder.workorder', verbose_name='orden de trabajo')),
            ],
            options={
                'verbose_name': 'informe de bombeo',
                'verbose_name_plural': 'informes de bombeo',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
